name: task_firebase
description: Using basic firebase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'



dependencies:
  path: any
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.4
  firebase_core_web: ^2.2.2
  firebase_auth_web: ^5.2.10
  intl: ^0.17.0 # Note that the right version of intl is also required.
  get: ^4.6.5
  provider: ^6.0.5
  get_it: ^7.2.0
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+3
  path_provider: ^2.0.14
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

 
  assets:
    - assets/images/
